var editingId = null;
var currentCollection = '';
var selectedCategoryFilter = '';

// ==================== DASHBOARD ====================
function loadDashboardPage(c) { c.innerHTML='<div class="stats-grid"><div class="stat-card"><div class="stat-icon"><i class="fas fa-utensils"></i></div><div class="stat-info"><span class="stat-label">Produits</span><span class="stat-value" id="productsCount">0</span></div></div><div class="stat-card"><div class="stat-icon"><i class="fas fa-users"></i></div><div class="stat-info"><span class="stat-label">Clients</span><span class="stat-value" id="clientsCount">0</span></div></div><div class="stat-card"><div class="stat-icon"><i class="fas fa-layer-group"></i></div><div class="stat-info"><span class="stat-label">Categories</span><span class="stat-value" id="categoriesCount">0</span></div></div><div class="stat-card"><div class="stat-icon"><i class="fas fa-shopping-cart"></i></div><div class="stat-info"><span class="stat-label">Ventes</span><span class="stat-value" id="ventesCount">0</span></div></div></div><div class="content-card"><div class="card-header"><h3><i class="fas fa-bell"></i> Inscriptions en attente</h3><button class="btn-add" onclick="loadPendingRegistrations()"><i class="fas fa-sync"></i></button></div><div id="pendingRegistrations">...</div></div>'; loadDashboardStats(); loadPendingRegistrations(); }
function loadDashboardStats() { db.collection('products').get().then(function(s){var e=document.getElementById('productsCount');if(e)e.textContent=s.size;}); db.collection('clients').get().then(function(s){var e=document.getElementById('clientsCount');if(e)e.textContent=s.size;}); db.collection('categories').get().then(function(s){var e=document.getElementById('categoriesCount');if(e)e.textContent=s.size;}); db.collection('ventes').get().then(function(s){var e=document.getElementById('ventesCount');if(e)e.textContent=s.size;}); }
function loadPendingRegistrations() { var d=document.getElementById('pendingRegistrations');if(!d)return;db.collection('users').where('authorized','==','no').get().then(function(s){if(s.empty){d.innerHTML='<p style="padding:30px;color:#16a34a;">Aucune</p>';return;}var u=[];s.forEach(function(dc){u.push({id:dc.id,data:dc.data()});});u.sort(function(a,b){return(b.data.createdAt?.seconds||0)-(a.data.createdAt?.seconds||0);});var h='<div class="table-container"><table class="data-table"><thead><tr><th>Utilisateur</th><th>Email</th><th>Role</th><th>Actions</th></tr></thead><tbody>';u.forEach(function(x){var dd=x.data,dt=dd.createdAt?new Date(dd.createdAt.seconds*1000).toLocaleDateString('fr-FR'):'';h+='<tr><td><strong>'+dd.prenom+' '+dd.nom+'</strong> (@'+dd.username+')<br><small>'+dt+'</small></td><td>'+dd.email+'</td><td>'+dd.role+'</td><td><button class="btn-add" style="padding:4px 8px;font-size:0.7rem;margin-right:5px;" onclick="approveUser(\''+x.id+'\')">Accepter</button><button class="btn-delete" style="padding:4px 8px;font-size:0.7rem;" onclick="rejectUser(\''+x.id+'\')">Refuser</button></td></tr>';});h+='</tbody></table></div>';d.innerHTML=h;});}
function approveUser(uid){if(confirm('Accepter ?')){db.collection('users').doc(uid).update({authorized:'yes',approvedAt:firebase.firestore.FieldValue.serverTimestamp()}).then(function(){alert('OK');loadPendingRegistrations();if(typeof loadUsersList==='function')loadUsersList();});}}
function rejectUser(uid){if(confirm('Refuser ?')){db.collection('users').doc(uid).delete().then(function(){alert('Supprime');loadPendingRegistrations();if(typeof loadUsersList==='function')loadUsersList();});}}

// ==================== MODAL ====================
function openModal(t,b){document.getElementById('modalTitle').textContent=t;document.getElementById('modalBody').innerHTML=b;document.getElementById('modalOverlay').classList.remove('hidden');}
function closeModal(){document.getElementById('modalOverlay').classList.add('hidden');editingId=null;currentCollection='';}
function fileToBase64(f,cb){if(!f){cb(null);return;}var r=new FileReader();r.onload=function(e){cb(e.target.result);};r.readAsDataURL(f);}
function previewImage(inp,pid){var p=document.getElementById(pid);if(!p)return;if(inp.files&&inp.files[0]){var r=new FileReader();r.onload=function(e){p.innerHTML='<img src="'+e.target.result+'" style="max-width:100px;margin-top:5px;border-radius:8px;">'};r.readAsDataURL(inp.files[0]);}}
function saveDocument(cn,data,cb){if(editingId){data.updatedAt=firebase.firestore.FieldValue.serverTimestamp();db.collection(cn).doc(editingId).update(data).then(function(){if(cb)cb();}).catch(function(err){alert(err.message);});}else{data.createdAt=firebase.firestore.FieldValue.serverTimestamp();db.collection(cn).add(data).then(function(){if(cb)cb();}).catch(function(err){alert(err.message);});}}
function editDocument(cn,id){db.collection(cn).doc(id).get().then(function(doc){if(doc.exists){editingId=id;currentCollection=cn;openEditForm(cn,doc.data());}});}
function deleteDocument(cn,id){if(confirm('Supprimer ?')){db.collection(cn).doc(id).delete().then(function(){alert('Supprime');refreshCurrentPage();}).catch(function(err){alert(err.message);});}}
function refreshCurrentPage(){var t=document.getElementById('pageTitle').textContent;var m={'Categories':'categories','Produits':'products','Clients':'clients','Fournisseurs':'fournisseurs','Depenses':'depenses','Ventes':'ventes','Credits':'credits'};navigateTo(m[t]||'dashboard');}

// ==================== CATEGORIES ====================
function loadCategoriesPage(c){c.innerHTML='<div class="content-card"><div class="card-header"><h3><i class="fas fa-layer-group"></i> Categories</h3><button class="btn-add" onclick="openCategoryForm()"><i class="fas fa-plus"></i> Nouvelle</button></div><div class="table-container"><table class="data-table"><thead><tr><th>Img</th><th>Nom</th><th>Desc</th><th>CA</th><th>Profit</th><th>Stock</th><th>Nb</th><th>Actions</th></tr></thead><tbody id="categoriesTable"></tbody></table></div></div>';loadCategories();}
async function loadCategories(){var tb=document.getElementById('categoriesTable');if(!tb)return;try{var sn=await db.collection('categories').orderBy('createdAt','desc').get();tb.innerHTML='';if(sn.empty){tb.innerHTML='<tr><td colspan="8">Aucune</td></tr>';return;}for(var i=0;i<sn.docs.length;i++){var d=sn.docs[i].data(),id=sn.docs[i].id;var pc=0;try{var ps=await db.collection('products').where('categorie','==',d.nom).get();pc=ps.size;}catch(e){}var im=d.imageBase64?'<img src="'+d.imageBase64+'" style="width:40px;height:40px;object-fit:cover;border-radius:8px;">':'<i class="fas fa-folder fa-2x" style="color:#f39c12;"></i>';var pcol=(d.profit||0)>=0?'#16a34a':'#dc2626';tb.innerHTML+='<tr><td>'+im+'</td><td><strong>'+d.nom+'</strong></td><td>'+(d.description||'-')+'</td><td>'+(d.ca||0).toFixed(2)+'</td><td style="color:'+pcol+';">'+(d.profit||0).toFixed(2)+'</td><td>'+(d.totalStock||0)+'</td><td>'+pc+'</td><td><button class="btn-edit" onclick="editDocument(\'categories\',\''+id+'\')"><i class="fas fa-edit"></i></button> <button class="btn-delete" onclick="deleteDocument(\'categories\',\''+id+'\')"><i class="fas fa-trash"></i></button></td></tr>';}}catch(e){tb.innerHTML='<tr><td colspan="8">Erreur</td></tr>';}}
function openCategoryForm(data){data=data||{};var ip=data.imageBase64?'<img src="'+data.imageBase64+'" style="max-width:100px;">':'';var h='<div class="form-row"><div class="form-group"><label>Image</label><input type="file" id="catImage" onchange="previewImage(this,\'catPreview\')"><div id="catPreview">'+ip+'</div></div></div><div class="form-row"><div class="form-group"><label>Nom *</label><input type="text" id="catNom" value="'+(data.nom||'')+'" required></div><div class="form-group"><label>Description</label><textarea id="catDesc">'+(data.description||'')+'</textarea></div></div><div class="form-row"><div class="form-group"><label>CA</label><input type="number" id="catCA" value="'+(data.ca||0)+'" step="0.01"></div><div class="form-group"><label>Profit</label><input type="number" id="catProfit" value="'+(data.profit||0)+'" step="0.01"></div></div><div class="form-row"><div class="form-group"><label>Stock</label><input type="number" id="catStock" value="'+(data.totalStock||0)+'"></div></div><button class="btn-cancel" onclick="closeModal()">Annuler</button><button class="btn-save" onclick="saveCategory()">Enregistrer</button>';currentCollection='categories';openModal(editingId?'Modifier':'Nouvelle',h);}
function saveCategory(){var n=document.getElementById('catNom').value;if(!n){alert('Nom obligatoire');return;}var f=document.getElementById('catImage').files[0];var sf=function(img){var d={nom:n,description:document.getElementById('catDesc').value,ca:parseFloat(document.getElementById('catCA').value)||0,profit:parseFloat(document.getElementById('catProfit').value)||0,totalStock:parseInt(document.getElementById('catStock').value)||0};if(img)d.imageBase64=img;saveDocument('categories',d,function(){closeModal();refreshCurrentPage();});};if(f)fileToBase64(f,sf);else sf(null);}

// ==================== PRODUITS ====================
function loadProductsPage(c){c.innerHTML='<div class="content-card"><div class="card-header"><h3><i class="fas fa-utensils"></i> Produits</h3><div style="display:flex;gap:10px;"><select id="categoryFilter" onchange="filterProducts()"><option value="">Toutes</option></select><button class="btn-add" onclick="openProductForm()"><i class="fas fa-plus"></i> Nouveau</button></div></div><div class="table-container"><table class="data-table"><thead><tr><th>Img</th><th>Nom</th><th>Cat</th><th>Achat</th><th>Vente</th><th>Profit</th><th>Promo</th><th>Stock</th><th>Dispo</th><th>Actions</th></tr></thead><tbody id="productsTable"></tbody></table></div></div>';loadCategoriesInFilter();loadProducts();}
async function loadCategoriesInFilter(){var s=document.getElementById('categoryFilter');if(!s)return;try{var sn=await db.collection('categories').get();sn.forEach(function(d){s.innerHTML+='<option value="'+d.data().nom+'">'+d.data().nom+'</option>';});}catch(e){}}
function filterProducts(){selectedCategoryFilter=document.getElementById('categoryFilter').value;loadProducts();}
async function loadProducts(){var tb=document.getElementById('productsTable');if(!tb)return;try{var sn=await db.collection('products').orderBy('createdAt','desc').get();tb.innerHTML='';if(sn.empty){tb.innerHTML='<tr><td colspan="10">Aucun</td></tr>';return;}for(var i=0;i<sn.docs.length;i++){var d=sn.docs[i].data(),id=sn.docs[i].id;if(selectedCategoryFilter&&d.categorie!==selectedCategoryFilter)continue;var profit=(d.prixPromo&&d.prixPromo>0?d.prixPromo:(d.prixVente||0))-(d.prixAchat||0);var im=d.imageBase64?'<img src="'+d.imageBase64+'" style="width:40px;height:40px;object-fit:cover;border-radius:8px;">':'<div style="width:40px;height:40px;background:#f1f5f9;border-radius:8px;display:flex;align-items:center;justify-content:center;"><i class="fas fa-utensils" style="color:#94a3b8;"></i></div>';var disp=d.disponible!==false?'<span class="status-success">Oui</span>':'<span class="status-danger">Non</span>';var prom=d.prixPromo&&d.prixPromo>0?'<span style="color:#dc2626;">'+d.prixPromo.toFixed(2)+'</span>':'-';var pc=profit>=0?'#16a34a':'#dc2626';tb.innerHTML+='<tr><td>'+im+'</td><td><strong>'+d.nom+'</strong></td><td>'+(d.categorie||'-')+'</td><td>'+(d.prixAchat||0).toFixed(2)+'</td><td>'+(d.prixVente||0).toFixed(2)+'</td><td style="color:'+pc+';">'+profit.toFixed(2)+'</td><td>'+prom+'</td><td>'+(d.stock||0)+'</td><td>'+disp+'</td><td><button class="btn-edit" onclick="editDocument(\'products\',\''+id+'\')"><i class="fas fa-edit"></i></button> <button class="btn-delete" onclick="deleteDocument(\'products\',\''+id+'\')"><i class="fas fa-trash"></i></button></td></tr>';}}catch(e){tb.innerHTML='<tr><td colspan="10">Erreur</td></tr>';}}
async function openProductForm(data){data=data||{};var co='';try{var cs=await db.collection('categories').get();cs.forEach(function(d){var sel=data.categorie===d.data().nom?'selected':'';co+='<option value="'+d.data().nom+'" '+sel+'>'+d.data().nom+'</option>';});}catch(e){}var ip=data.imageBase64?'<img src="'+data.imageBase64+'" style="max-width:100px;">':'';var dy=data.disponible!==false?'selected':'',dn=data.disponible===false?'selected':'';var h='<div class="form-row"><div class="form-group"><label>Image</label><input type="file" id="prodImage" onchange="previewImage(this,\'prodPreview\')"><div id="prodPreview">'+ip+'</div></div></div><div class="form-row"><div class="form-group"><label>Nom *</label><input type="text" id="prodNom" value="'+(data.nom||'')+'" required></div><div class="form-group"><label>Categorie</label><select id="prodCat"><option value="">-</option>'+co+'</select></div></div><div class="form-row"><div class="form-group"><label>Achat</label><input type="number" id="prodPA" value="'+(data.prixAchat||0)+'" step="0.01" onchange="calcP()"></div><div class="form-group"><label>Vente</label><input type="number" id="prodPV" value="'+(data.prixVente||0)+'" step="0.01" onchange="calcP()"></div></div><div class="form-row"><div class="form-group"><label>Promo</label><input type="number" id="prodPromo" value="'+(data.prixPromo||0)+'" step="0.01" onchange="calcP()"></div><div class="form-group"><label>Profit: <span id="profitPreview">0</span></label></div></div><div class="form-row"><div class="form-group"><label>Stock</label><input type="number" id="prodStock" value="'+(data.stock||0)+'"></div><div class="form-group"><label>Temps</label><input type="text" id="prodTemps" value="'+(data.tempsPrep||'')+'"></div></div><div class="form-row"><div class="form-group"><label>Dispo</label><select id="prodDispo"><option value="1" '+dy+'>Oui</option><option value="0" '+dn+'>Non</option></select></div><div class="form-group"><label>Description</label><textarea id="prodDesc">'+(data.description||'')+'</textarea></div></div><button class="btn-cancel" onclick="closeModal()">Annuler</button><button class="btn-save" onclick="saveProduct()">Enregistrer</button>';currentCollection='products';openModal(editingId?'Modifier':'Nouveau',h);setTimeout(calcP,100);}
function calcP(){var pa=parseFloat(document.getElementById('prodPA').value)||0,pv=parseFloat(document.getElementById('prodPV').value)||0,pr=parseFloat(document.getElementById('prodPromo').value)||0,pf=pr>0?pr:pv,profit=pf-pa;var el=document.getElementById('profitPreview');if(el){el.textContent=profit.toFixed(2)+' MAD';el.style.color=profit>=0?'#16a34a':'#dc2626';}}
function saveProduct(){var n=document.getElementById('prodNom').value;if(!n){alert('Nom obligatoire');return;}var f=document.getElementById('prodImage').files[0],pa=parseFloat(document.getElementById('prodPA').value)||0,pv=parseFloat(document.getElementById('prodPV').value)||0,pr=parseFloat(document.getElementById('prodPromo').value)||0,pf=pr>0?pr:pv;var sf=function(img){var d={nom:n,categorie:document.getElementById('prodCat').value,prixAchat:pa,prixVente:pv,prixPromo:pr,profit:pf-pa,stock:parseInt(document.getElementById('prodStock').value)||0,vendues:0,ca:0,tempsPrep:document.getElementById('prodTemps').value,disponible:document.getElementById('prodDispo').value==='1',description:document.getElementById('prodDesc').value};if(img)d.imageBase64=img;saveDocument('products',d,function(){closeModal();refreshCurrentPage();});};if(f)fileToBase64(f,sf);else sf(null);}

// ==================== CLIENTS (COMPLET) ====================
function loadAllClientsPage(c){c.innerHTML='<div class="content-card"><div class="card-header"><h3><i class="fas fa-users"></i> Clients</h3><button class="btn-add" onclick="openClientForm()"><i class="fas fa-plus"></i> Ajouter</button></div><div class="table-container"><table class="data-table" style="font-size:0.7rem;"><thead><tr><th>ID</th><th>Nom</th><th>Prenom</th><th>Tel</th><th>CA</th><th>Profit</th><th>Credit</th><th>Remise</th><th>Actions</th></tr></thead><tbody id="clientsTable"></tbody></table></div></div>';loadAllClients();}
async function loadAllClients(){var tb=document.getElementById('clientsTable');if(!tb)return;try{var sn=await db.collection('clients').orderBy('createdAt','desc').get();tb.innerHTML='';if(sn.empty){tb.innerHTML='<tr><td colspan="9">Aucun</td></tr>';return;}for(var i=0;i<sn.docs.length;i++){var d=sn.docs[i].data(),id=sn.docs[i].id;tb.innerHTML+='<tr><td><small>'+id.substring(0,6)+'</small></td><td><strong>'+(d.nom||'')+'</strong></td><td>'+(d.prenom||'')+'</td><td>'+(d.telephone||'-')+'</td><td>'+(d.ca||0).toFixed(2)+'</td><td style="color:#16a34a;">'+(d.profit||0).toFixed(2)+'</td><td style="color:#ef4444;">'+(d.credit||0).toFixed(2)+'</td><td>'+(d.remise||0)+'%</td><td><button class="btn-edit" onclick="editClient(\''+id+'\')"><i class="fas fa-edit"></i></button> <button class="btn-delete" onclick="deleteClient(\''+id+'\')"><i class="fas fa-trash"></i></button></td></tr>';}}catch(e){tb.innerHTML='<tr><td colspan="9">Erreur</td></tr>';}}
function openClientForm(data){data=data||{};var h='<div class="form-row"><div class="form-group"><label>Nom *</label><input type="text" id="cliNom" value="'+(data.nom||'')+'" required></div><div class="form-group"><label>Prenom *</label><input type="text" id="cliPrenom" value="'+(data.prenom||'')+'" required></div></div>';h+='<div class="form-row"><div class="form-group"><label>Genre</label><select id="cliGenre"><option value="">-</option><option value="Homme" '+(data.genre==='Homme'?'selected':'')+'>Homme</option><option value="Femme" '+(data.genre==='Femme'?'selected':'')+'>Femme</option></select></div><div class="form-group"><label>Adresse</label><input type="text" id="cliAdresse" value="'+(data.adresse||'')+'"></div></div>';h+='<div class="form-row"><div class="form-group"><label>Telephone</label><input type="text" id="cliTel" value="'+(data.telephone||'')+'"></div><div class="form-group"><label>WhatsApp</label><input type="text" id="cliWhatsapp" value="'+(data.whatsapp||'')+'"></div></div>';h+='<div class="form-row"><div class="form-group"><label>Instagram</label><input type="text" id="cliInstagram" value="'+(data.instagram||'')+'"></div><div class="form-group"><label>Email</label><input type="email" id="cliEmail" value="'+(data.email||'')+'"></div></div>';h+='<div class="form-row"><div class="form-group"><label>CA</label><input type="number" id="cliCA" value="'+(data.ca||0)+'" step="0.01"></div><div class="form-group"><label>Profit</label><input type="number" id="cliProfit" value="'+(data.profit||0)+'" step="0.01"></div></div>';h+='<div class="form-row"><div class="form-group"><label>Credit</label><input type="number" id="cliCredit" value="'+(data.credit||0)+'" step="0.01"></div><div class="form-group"><label>Remise (%)</label><input type="number" id="cliRemise" value="'+(data.remise||0)+'" min="0" max="100"></div></div>';h+='<div class="form-row"><div class="form-group"><label>Allergies (virgule)</label><input type="text" id="cliAllergies" value="'+(data.allergies?data.allergies.join(', '):'')+'" placeholder="gluten, lactose"></div><div class="form-group"><label>Preferences (virgule)</label><input type="text" id="cliPreferences" value="'+(data.preferences?data.preferences.join(', '):'')+'" placeholder="poulet, poisson"></div></div>';h+='<div class="form-row"><div class="form-group"><label>Deteste (virgule)</label><input type="text" id="cliDeteste" value="'+(data.deteste?data.deteste.join(', '):'')+'" placeholder="oignon, tomate"></div><div class="form-group"><label>Description</label><textarea id="cliDesc">'+(data.description||'')+'</textarea></div></div>';h+='<button class="btn-cancel" onclick="closeModal()">Annuler</button><button class="btn-save" onclick="saveClient()">Enregistrer</button>';currentCollection='clients';openModal(editingId?'Modifier Client':'Nouveau Client',h);}
function saveClient(){var n=document.getElementById('cliNom').value,p=document.getElementById('cliPrenom').value;if(!n||!p){alert('Nom et Prenom obligatoires');return;}var d={nom:n,prenom:p,genre:document.getElementById('cliGenre').value,adresse:document.getElementById('cliAdresse').value,telephone:document.getElementById('cliTel').value,whatsapp:document.getElementById('cliWhatsapp').value,instagram:document.getElementById('cliInstagram').value,email:document.getElementById('cliEmail').value,ca:parseFloat(document.getElementById('cliCA').value)||0,profit:parseFloat(document.getElementById('cliProfit').value)||0,credit:parseFloat(document.getElementById('cliCredit').value)||0,remise:parseFloat(document.getElementById('cliRemise').value)||0,allergies:document.getElementById('cliAllergies').value.split(',').map(function(s){return s.trim();}).filter(Boolean),preferences:document.getElementById('cliPreferences').value.split(',').map(function(s){return s.trim();}).filter(Boolean),deteste:document.getElementById('cliDeteste').value.split(',').map(function(s){return s.trim();}).filter(Boolean),description:document.getElementById('cliDesc').value};if(!editingId)d.createdAt=firebase.firestore.FieldValue.serverTimestamp();saveDocument('clients',d,function(){closeModal();loadAllClients();});}
function editClient(id){db.collection('clients').doc(id).get().then(function(doc){if(doc.exists){editingId=id;currentCollection='clients';openClientForm(doc.data());}});}
function deleteClient(id){if(confirm('Supprimer ?')){db.collection('clients').doc(id).delete().then(function(){alert('Supprime');loadAllClients();});}}

// Suite dans la PARTIE 2...
console.log('Admin JS Part 1 OK');

// ==================== FOURNISSEURS ====================
function loadFournisseursPage(c){c.innerHTML='<div class="content-card"><div class="card-header"><h3><i class="fas fa-truck"></i> Fournisseurs</h3><button class="btn-add" onclick="openFournisseurForm()"><i class="fas fa-plus"></i> Ajouter</button></div><div class="table-container"><table class="data-table"><thead><tr><th>Nom</th><th>Prenom</th><th>Tel</th><th>Actions</th></tr></thead><tbody id="fournisseursTable"></tbody></table></div></div>';db.collection('fournisseurs').orderBy('createdAt','desc').get().then(function(sn){var tb=document.getElementById('fournisseursTable');tb.innerHTML='';if(sn.empty){tb.innerHTML='<tr><td colspan="4">Aucun</td></tr>';return;}sn.forEach(function(dc){var d=dc.data();tb.innerHTML+='<tr><td><strong>'+d.nom+'</strong></td><td>'+d.prenom+'</td><td>'+(d.telephone||'-')+'</td><td><button class="btn-edit" onclick="editDocument(\'fournisseurs\',\''+dc.id+'\')"><i class="fas fa-edit"></i></button> <button class="btn-delete" onclick="deleteDocument(\'fournisseurs\',\''+dc.id+'\')"><i class="fas fa-trash"></i></button></td></tr>';});});}
function openFournisseurForm(data){data=data||{};var h='<div class="form-row"><div class="form-group"><label>Nom *</label><input type="text" id="fourNom" value="'+(data.nom||'')+'" required></div><div class="form-group"><label>Prenom *</label><input type="text" id="fourPrenom" value="'+(data.prenom||'')+'" required></div></div><div class="form-row"><div class="form-group"><label>Tel</label><input type="text" id="fourTel" value="'+(data.telephone||'')+'"></div><div class="form-group"><label>Description</label><textarea id="fourDesc">'+(data.description||'')+'</textarea></div></div><button class="btn-cancel" onclick="closeModal()">Annuler</button><button class="btn-save" onclick="saveFournisseur()">Enregistrer</button>';currentCollection='fournisseurs';openModal(editingId?'Modifier':'Nouveau',h);}
function saveFournisseur(){var n=document.getElementById('fourNom').value,p=document.getElementById('fourPrenom').value;if(!n||!p){alert('Nom et Prenom obligatoires');return;}saveDocument('fournisseurs',{nom:n,prenom:p,telephone:document.getElementById('fourTel').value,description:document.getElementById('fourDesc').value},function(){closeModal();refreshCurrentPage();});}

// ==================== DEPENSES ====================
function loadDepensesPage(c){c.innerHTML='<div class="content-card"><div class="card-header"><h3><i class="fas fa-money-bill-wave"></i> Depenses</h3><button class="btn-add" onclick="openDepenseForm()"><i class="fas fa-plus"></i> Ajouter</button></div><div class="table-container"><table class="data-table"><thead><tr><th>Date</th><th>Description</th><th>Montant</th><th>Actions</th></tr></thead><tbody id="depensesTable"></tbody></table></div></div>';db.collection('depenses').orderBy('createdAt','desc').get().then(function(sn){var tb=document.getElementById('depensesTable');tb.innerHTML='';if(sn.empty){tb.innerHTML='<tr><td colspan="4">Aucune</td></tr>';return;}sn.forEach(function(dc){var d=dc.data();tb.innerHTML+='<tr><td>'+(d.date||'-')+'</td><td>'+(d.description||'-')+'</td><td><strong style="color:#ef4444;">'+(d.montant||0).toFixed(2)+'</strong></td><td><button class="btn-edit" onclick="editDocument(\'depenses\',\''+dc.id+'\')"><i class="fas fa-edit"></i></button> <button class="btn-delete" onclick="deleteDocument(\'depenses\',\''+dc.id+'\')"><i class="fas fa-trash"></i></button></td></tr>';});});}
function openDepenseForm(data){data=data||{};var h='<div class="form-row"><div class="form-group"><label>Date</label><input type="date" id="depDate" value="'+(data.date||new Date().toISOString().split('T')[0])+'"></div><div class="form-group"><label>Montant *</label><input type="number" id="depMontant" value="'+(data.montant||0)+'" step="0.01" required></div></div><div class="form-row"><div class="form-group"><label>Description</label><textarea id="depDesc">'+(data.description||'')+'</textarea></div></div><button class="btn-cancel" onclick="closeModal()">Annuler</button><button class="btn-save" onclick="saveDepense()">Enregistrer</button>';currentCollection='depenses';openModal(editingId?'Modifier':'Nouvelle',h);}
function saveDepense(){var m=parseFloat(document.getElementById('depMontant').value)||0;if(!m){alert('Montant obligatoire');return;}saveDocument('depenses',{date:document.getElementById('depDate').value,montant:m,description:document.getElementById('depDesc').value},function(){closeModal();refreshCurrentPage();});}
function openEditForm(cn,data){if(cn==='categories')openCategoryForm(data);else if(cn==='products')openProductForm(data);else if(cn==='clients')openClientForm(data);else if(cn==='fournisseurs')openFournisseurForm(data);else if(cn==='depenses')openDepenseForm(data);}

// ==================== COMMANDES EN LIGNE ====================
function loadCommandesPage(c){c.innerHTML='<div class="content-card"><div class="card-header"><h3><i class="fas fa-shopping-basket"></i> Commandes en ligne</h3><button class="btn-add" onclick="loadCommandes()"><i class="fas fa-sync"></i></button></div><div id="commandesTableContainer">...</div></div>';loadCommandes();}
function loadCommandes(){var cont=document.getElementById('commandesTableContainer');if(!cont)return;db.collection('commandes').orderBy('createdAt','desc').limit(50).get().then(function(sn){if(sn.empty){cont.innerHTML='<p style="text-align:center;padding:40px;">Aucune</p>';return;}var h='<div class="table-container"><table class="data-table" style="font-size:0.75rem;"><thead><tr><th>Date</th><th>Client</th><th>Contact</th><th>Detail</th><th>Total</th><th>Statut</th><th colspan="2">Actions</th></tr></thead><tbody>';sn.forEach(function(dc){var d=dc.data();var date=d.createdAt?new Date(d.createdAt.seconds*1000).toLocaleString('fr-FR'):'';var det=d.items?d.items.map(function(it){return it.quantite+'x '+it.nom;}).join(', '):'';var sc=d.statut==='valide'?'#16a34a':d.statut==='en_attente'?'#d97706':'#94a3b8';var sl=d.statut==='valide'?'Validée':d.statut==='en_attente'?'En attente':d.statut||'?';var act=d.statut==='en_attente'?'<button class="btn-add" style="padding:4px 8px;font-size:0.7rem;margin-right:5px;" onclick="validateCommande(\''+dc.id+'\')">Valider</button><button class="btn-delete" style="padding:4px 8px;font-size:0.7rem;" onclick="cancelCommande(\''+dc.id+'\')">Annuler</button>':'<small>'+(d.validatedBy||'')+'</small>';h+='<tr><td>'+date+'</td><td><strong>'+(d.clientName||'')+'</strong></td><td><small>'+(d.clientTelephone||'')+'<br>'+(d.clientEmail||'')+'</small></td><td><small>'+det+'</small></td><td>'+d.total.toFixed(2)+' MAD</td><td><span style="color:'+sc+';">'+sl+'</span></td><td>'+act+'</td></tr>';});h+='</tbody></table></div>';cont.innerHTML=h;});}
async function validateCommande(cid){if(!confirm('Valider?'))return;var dc=await db.collection('commandes').doc(cid).get();if(!dc.exists)return;var cmd=dc.data();var fcs=await db.collection('ventes').get();var fn='FACT-'+new Date().getFullYear()+'-'+String(fcs.size+1).padStart(5,'0');await db.collection('ventes').add({factureNum:fn,items:cmd.items,total:cmd.total,subtotal:cmd.total,discount:0,clientId:cmd.clientId,clientName:cmd.clientName,paymentMethod:'espece',amountGiven:cmd.total,change:0,paid:true,remainingAmount:0,vendeur:window.currentUserData?window.currentUserData.userData.prenom+' '+window.currentUserData.userData.nom:'Admin',createdAt:firebase.firestore.FieldValue.serverTimestamp(),source:'commande_en_ligne'});if(cmd.items){for(var it of cmd.items){try{var pr=await db.collection('products').doc(it.id).get();if(pr.exists){var pd=pr.data();await db.collection('products').doc(it.id).update({stock:Math.max(0,(pd.stock||0)-it.quantite),vendues:(pd.vendues||0)+it.quantite,ca:(pd.ca||0)+(it.prixUnitaire*it.quantite),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});}}catch(e){}}}await db.collection('commandes').doc(cid).update({statut:'valide',validatedAt:firebase.firestore.FieldValue.serverTimestamp(),validatedBy:window.currentUserData?window.currentUserData.userData.prenom+' '+window.currentUserData.userData.nom:'Admin'});alert('Validee !');loadCommandes();}
function cancelCommande(cid){if(confirm('Annuler?')){db.collection('commandes').doc(cid).update({statut:'annule'});alert('Annulee');loadCommandes();}}

// ==================== VENTES ====================
function loadVentesPage(c){c.innerHTML='<div class="content-card"><div class="card-header"><h3><i class="fas fa-shopping-cart"></i> Ventes</h3><button class="btn-add" onclick="loadVentes()"><i class="fas fa-sync"></i></button></div><div id="ventesTableContainer">...</div></div>';loadVentes();}
function loadVentes(){var cont=document.getElementById('ventesTableContainer');if(!cont)return;var isAdmin=window.currentUserData&&window.currentUserData.userData.role==='admin';db.collection('ventes').orderBy('createdAt','desc').limit(100).get().then(function(sn){if(sn.empty){cont.innerHTML='<p style="text-align:center;padding:40px;">Aucune</p>';return;}var tv=0;var h='<div class="table-container"><table class="data-table" style="font-size:0.7rem;"><thead><tr><th>Facture</th><th>Date</th><th>Client</th><th>Articles</th>'+(isAdmin?'<th>Achat</th><th>Profit</th>':'')+'<th>Total</th><th>Vendeur</th><th>Paiement</th><th>Payé</th><th>Actions</th></tr></thead><tbody>';sn.forEach(function(dc){var d=dc.data();var dt=d.createdAt?new Date(d.createdAt.seconds*1000).toLocaleString('fr-FR'):'';var cl=d.clientName||d.table||'-';var arts=d.items?d.items.map(function(it){return it.nom;}).join(', '):'-';var achat=d.items?d.items.reduce(function(s,it){return s+(it.prixAchat||0)*it.quantite;},0):0;var profit=d.items?d.items.reduce(function(s,it){return s+((it.prixVente-(it.prixAchat||0))*it.quantite);},0):0;tv+=d.total||0;h+='<tr><td><strong>'+(d.factureNum||dc.id.substring(0,8))+'</strong></td><td>'+dt+'</td><td>'+cl+'</td><td><small>'+arts+'</small></td>'+(isAdmin?'<td>'+achat.toFixed(2)+'</td><td style="color:#16a34a;">'+profit.toFixed(2)+'</td>':'')+'<td><strong>'+d.total.toFixed(2)+'</strong></td><td>'+(d.vendeur||'-')+'</td><td>'+(d.paymentMethod==='espece'?'Espèces':d.paymentMethod==='credit'?'Crédit':'Partiel')+'</td><td>'+(d.paid?'<span class="status-success">Oui</span>':'<span class="status-danger">Non</span>')+'</td><td><button class="btn-edit" onclick="printFacture(\''+dc.id+'\')"><i class="fas fa-print"></i></button> '+(isAdmin?'<button class="btn-edit" onclick="editVente(\''+dc.id+'\')"><i class="fas fa-edit"></i></button> <button class="btn-delete" onclick="deleteVente(\''+dc.id+'\')"><i class="fas fa-trash"></i></button>':'')+'</td></tr>';});h+='</tbody></table></div><div style="margin-top:15px;padding:15px;background:#f0fdf4;border-radius:12px;text-align:center;"><strong>Total: '+tv.toFixed(2)+' MAD</strong></div>';cont.innerHTML=h;});}

// ==================== CREDITS ====================
function loadCreditsPage(c){c.innerHTML='<div class="content-card"><div class="card-header"><h3><i class="fas fa-credit-card"></i> Credits</h3><button class="btn-add" onclick="loadCredits()"><i class="fas fa-sync"></i></button></div><div id="creditsTableContainer">...</div></div>';loadCredits();}
function loadCredits(){var cont=document.getElementById('creditsTableContainer');if(!cont)return;db.collection('credits').orderBy('createdAt','desc').limit(100).get().then(function(sn){if(sn.empty){cont.innerHTML='<p style="text-align:center;padding:40px;">Aucun</p>';return;}var tc=0;var h='<div class="table-container"><table class="data-table" style="font-size:0.7rem;"><thead><tr><th>Facture</th><th>Date</th><th>Client</th><th>Total</th><th>Payé</th><th>Reste</th><th>Vendeur</th><th>Actions</th></tr></thead><tbody>';sn.forEach(function(dc){var d=dc.data();var reste=d.remainingAmount||d.total||0;if(!d.paid)tc+=reste;var dt=d.createdAt?new Date(d.createdAt.seconds*1000).toLocaleString('fr-FR'):'';h+='<tr><td>'+(d.factureNum||dc.id.substring(0,8))+'</td><td>'+dt+'</td><td>'+(d.clientName||d.table||'-')+'</td><td>'+d.total.toFixed(2)+'</td><td>'+(d.amountGiven||0).toFixed(2)+'</td><td style="color:#ef4444;"><strong>'+reste.toFixed(2)+'</strong></td><td>'+(d.vendeur||'-')+'</td><td><button class="btn-edit" onclick="printFacture(\''+dc.id+'\')"><i class="fas fa-print"></i></button> '+(d.paid?'':'<button class="btn-add" style="padding:4px 8px;font-size:0.65rem;" onclick="markCreditPaid(\''+dc.id+'\')">Payer</button>')+'</td></tr>';});h+='</tbody></table></div><div style="margin-top:15px;padding:15px;background:#fef2f2;border-radius:12px;text-align:center;"><strong>Impayés: '+tc.toFixed(2)+' MAD</strong></div>';cont.innerHTML=h;});}
function markCreditPaid(cid){if(confirm('Payé ?')){db.collection('credits').doc(cid).update({paid:true,remainingAmount:0,paidAt:firebase.firestore.FieldValue.serverTimestamp()}).then(function(){loadCredits();});}}

// ==================== ACTIONS ====================
function printFacture(did){db.collection('ventes').doc(did).get().then(function(dc){if(dc.exists)imprimerFacture(dc.data(),dc.id);else{db.collection('credits').doc(did).get().then(function(cd){if(cd.exists)imprimerFacture(cd.data(),cd.id);});}});}
function imprimerFacture(d,id){var ih='';if(d.items){d.items.forEach(function(it){var o='';if(it.interdits&&it.interdits.length>0)o+=' 🚫'+it.interdits.join(',');if(it.permis&&it.permis.length>0)o+=' ✅'+it.permis.join(',');if(it.epice&&it.epice!=='Normal')o+=' 🌶️'+it.epice;ih+='<tr><td>'+it.nom+o+'</td><td>'+it.quantite+'</td><td>'+it.prixVente.toFixed(2)+'</td><td>'+(it.prixVente*it.quantite).toFixed(2)+'</td></tr>';});}var w=window.open('','_blank','width=400,height=600');w.document.write('<html><head><title>Facture</title><style>body{font-family:Arial;padding:20px;}h2{text-align:center;}table{width:100%;border-collapse:collapse;}th,td{padding:5px;border-bottom:1px solid #ddd;}.total{font-size:16px;font-weight:bold;text-align:right;}</style></head><body><h2>🐔 Chicken Way</h2><p>Facture: '+(d.factureNum||id.substring(0,8))+'</p><p>Date: '+(d.createdAt?new Date(d.createdAt.seconds*1000).toLocaleString('fr-FR'):'')+'</p><p>Client: '+(d.clientName||d.table||'')+'</p><p>Vendeur: '+(d.vendeur||'-')+'</p><table><tr><th>Article</th><th>Qté</th><th>Prix</th><th>Total</th></tr>'+ih+'</table>'+(d.discount>0?'<p>Remise: '+d.discount+'%</p>':'')+'<p class="total">Total: '+d.total.toFixed(2)+' MAD</p></body></html>');w.document.close();setTimeout(function(){w.print();},500);}
function editVente(did){db.collection('ventes').doc(did).get().then(function(dc){if(dc.exists){editingId=did;currentCollection='ventes';var d=dc.data();var h='<div class="form-row"><div class="form-group"><label>Statut</label><select id="editPaid"><option value="1" '+(d.paid?'selected':'')+'>Payé</option><option value="0" '+(!d.paid?'selected':'')+'>Impayé</option></select></div><div class="form-group"><label>Reste</label><input type="number" id="editRemaining" value="'+(d.remainingAmount||0)+'" step="0.01"></div></div><button class="btn-cancel" onclick="closeModal()">Annuler</button><button class="btn-save" onclick="saveEditVente()">Enregistrer</button>';openModal('Modifier',h);}});}
function saveEditVente(){var p=document.getElementById('editPaid').value==='1';var r=parseFloat(document.getElementById('editRemaining').value)||0;saveDocument(currentCollection,{paid:p,remainingAmount:p?0:r},function(){closeModal();refreshCurrentPage();});}
function deleteVente(did){if(confirm('Supprimer ?')){db.collection('ventes').doc(did).delete().then(function(){alert('OK');refreshCurrentPage();});}}

// ==================== OPTIONS ====================
function loadOptionsPage(c){if(!window.currentUserData||window.currentUserData.userData.role!=='admin'){c.innerHTML='<p>Acces refuse</p>';return;}c.innerHTML='<div class="stats-grid"><div class="stat-card"><div class="stat-icon" style="background:#fef3c7;"><i class="fas fa-clock" style="color:#d97706;"></i></div><div class="stat-info"><span>En attente</span><span class="stat-value" id="pendingCount">0</span></div></div><div class="stat-card"><div class="stat-icon" style="background:#dcfce7;"><i class="fas fa-check-circle" style="color:#16a34a;"></i></div><div class="stat-info"><span>Autorises</span><span class="stat-value" id="authorizedCount">0</span></div></div><div class="stat-card"><div class="stat-icon" style="background:#e0e7ff;"><i class="fas fa-users" style="color:#4f46e5;"></i></div><div class="stat-info"><span>Total</span><span class="stat-value" id="totalUsers">0</span></div></div></div><div class="content-card"><div class="card-header"><h3>Utilisateurs</h3><button class="btn-add" onclick="loadUsersList()">Actualiser</button></div><div class="table-container"><table class="data-table"><thead><tr><th>Username</th><th>Nom</th><th>Email</th><th>Role</th><th>Statut</th><th>Actions</th></tr></thead><tbody id="usersTableBody"></tbody></table></div></div>';loadUsersList();}
function loadUsersList(){db.collection('users').get().then(function(sn){var p=0,a=0;var tb=document.getElementById('usersTableBody');tb.innerHTML='';if(sn.empty){tb.innerHTML='<tr><td colspan="6">Aucun</td></tr>';}var us=[];sn.forEach(function(dc){us.push({id:dc.id,data:dc.data()});});us.sort(function(x,y){return(y.data.createdAt?.seconds||0)-(x.data.createdAt?.seconds||0);});us.forEach(function(u){var d=u.data,id=u.id;if(d.authorized==='no')p++;else a++;var badge=d.authorized==='yes'?'<span class="status-success">OK</span>':'<span class="status-warning">En attente</span>';var act=d.authorized==='no'?'<button class="btn-add" style="padding:4px 8px;font-size:0.7rem;margin-right:5px;" onclick="approveUser(\''+id+'\')">Accepter</button><button class="btn-delete" style="padding:4px 8px;font-size:0.7rem;" onclick="rejectUser(\''+id+'\')">Refuser</button>':'<button style="padding:4px 8px;font-size:0.7rem;margin-right:5px;color:#d97706;border:none;cursor:pointer;background:#fef3c7;border-radius:6px;" onclick="blockUser(\''+id+'\')">Bloquer</button><button class="btn-delete" style="padding:4px 8px;font-size:0.7rem;" onclick="deleteUserPermanently(\''+id+'\')">Supprimer</button>';tb.innerHTML+='<tr><td>@'+d.username+'</td><td>'+d.prenom+' '+d.nom+'</td><td>'+d.email+'</td><td>'+d.role+'</td><td>'+badge+'</td><td>'+act+'</td></tr>';});document.getElementById('pendingCount').textContent=p;document.getElementById('authorizedCount').textContent=a;document.getElementById('totalUsers').textContent=sn.size;});}
function blockUser(uid){if(confirm('Bloquer?')){db.collection('users').doc(uid).update({authorized:'no'}).then(function(){loadUsersList();loadPendingRegistrations();});}}
function deleteUserPermanently(uid){if(confirm('Supprimer?')){db.collection('users').doc(uid).delete().then(function(){loadUsersList();loadPendingRegistrations();});}}

console.log('Admin JS OK');

